//go:build ignore
// +build ignore

package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"os"
	"strings"
)

const jsonFilePath = "chains/chains_mini.json"
const outputGoFile = "chains/chains.go"

type Chain struct {
	Name           string         `json:"name"`
	ChainId        uint64         `json:"chainId"`
	ShortName      string         `json:"shortName"`
	NetworkId      uint64         `json:"networkId"`
	NativeCurrency NativeCurrency `json:"nativeCurrency"`
	RPC            []string       `json:"rpc"`
}

type NativeCurrency struct {
	Name     string `json:"name"`
	Symbol   string `json:"symbol"`
	Decimals uint64 `json:"decimals"`
}

func main() {
	file, err := os.Open(jsonFilePath)
	if err != nil {
		log.Panicf("failed to open JSON file: %v", err)
	}
	defer file.Close()

	body, err := io.ReadAll(file)
	if err != nil {
		log.Panicf("failed to read JSON file: %v", err)
	}

	var chainList []*Chain
	if err := json.Unmarshal(body, &chainList); err != nil {
		log.Panicf("failed to parse JSON: %v", err)
	}

	// ok, generate

	var sb strings.Builder

	sb.WriteString(`package chains

// Code generated by generate.go; DO NOT EDIT.

type Chain struct {
	Name           string     
	ChainId        uint64   
	ShortName      string  
	NetworkId      uint64    
	NativeCurrency NativeCurrency 
	RPC            []string  
}

type NativeCurrency struct {
	Name     string
	Symbol   string 
	Decimals uint64 
}

var Chains = map[uint64]Chain{
`)

	for _, chain := range chainList {
		// chainJSON, _ := json.MarshalIndent(chain, "", "    ") // Pretty-print JSON

		rpcList := make([]string, len(chain.RPC))
		for i, v := range chain.RPC {
			rpcList[i] = fmt.Sprintf(`"%s"`, v)
		}

		chainJSON := fmt.Sprintf(`Chain{
		Name:      "%s",
		ChainId:   %d,
		ShortName: "%s",
		NetworkId: %d,
		NativeCurrency: NativeCurrency{
			Name:     "%s",
			Symbol:   "%s",
			Decimals: %d,
		},
		RPC: []string{%s},
	}`, chain.Name, chain.ChainId, chain.ShortName, chain.NetworkId,
			chain.NativeCurrency.Name, chain.NativeCurrency.Symbol, chain.NativeCurrency.Decimals,
			strings.Join(rpcList, ","))
		sb.WriteString(fmt.Sprintf("\t%d: %s,\n", chain.ChainId, string(chainJSON)))
	}

	sb.WriteString("}\n")

	// Write to file
	err = os.WriteFile(outputGoFile, []byte(sb.String()), 0644)
	if err != nil {
		log.Panicf("failed to write JSON file: %v", err)
	}
}
